# version 1.0
name: CI - Build and push to Github Container Registry
on:
  push:
    tags:
      - '*'

jobs:
  build:
    name: Build and push
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2
        
      - name: Agregar envs
        run: |
          echo "${{ secrets.ENV_LOCAL }}" > .env.local

      - uses: mr-smithers-excellent/docker-build-push@v5
        name: Build & push Docker image
        with:
          image: adminorg
          registry: ghcr.io
          username: ${{ secrets.GHCR_USERNAME }}
          password: ${{ secrets.GHCR_TOKEN }} 
